### PR TITLE
Refactor JSONWriter

### PR DESCRIPTION
**Pull request by MaxNoe**
This includes the following changes:

* `json` format by default, optional `jsonl` format by using `jsonl="true"` in the `xml`
* New `append` option, default is false, so existing files are overwritten.
* The `keys` key is now evaluated using the `stream.Keys` class, so glob patterns now work.
* Increase version number to 0.12 because these changes break xmls.

No xmls in the example folder needed to be changed, although they are no behaving differently (output is `json`, not `jsonl` now).

One might want to add an Option to convert `Infinity`, `-Infinity` and `NaN` to something strictly `json` compatible.

What would you like? `null`? Or strings like `"nan", "inf", "-inf"`

### CODE REVIEW

**Comment by MaxNoe** [comment]
See issues #92, #73

**Comment by dneise** [comment]
what is `jsonl`?

**Comment by MaxNoe** [comment]
http://jsonlines.org/

**Comment by dneise** [comment]
Suggested Conventions

JSON Lines files may be saved with the file extension .jsonl.

**Comment by MaxNoe** [comment]
The filename is choosen by the user.

**Comment by dneise** [comment]
a pity ..

**Comment by MaxNoe** [comment]
I added an option to serialize the special values to strings `"inf"`, `"-inf"`, `"nan"`.

I am not sure about a sensible default. Right now it is `false`, so `Infinity`, `-Infinity` and `NaN` are used by default.

What should the default be?

**Comment by dneise** [comment]
I'm very glad this issue was discussed extensively here

**Pull request merged**
