### PR TITLE
Use AuxFileService in examples/forErna/std_analysis_erna_observations.xml

### PR DESCRIPTION
**Pull request by jebuss**
The `SqliteService` is not needed anymore since the `AuxFileService` is able to go through the entire directory tree

### CODE REVIEW

**Comment by MaxNoe** [comment]
We could also completely remove the `SqliteService`

**Comment by jebuss** [comment]
this will fix part 1 of #353

**Comment by jebuss** [comment]
fixes #353

**Comment by jebuss** [comment]
fixes #351

**Pull request merged**
