### PR TITLE
Remove output from unit tests

### PR DESCRIPTION
**Pull request by mackaiver**
This removes some noise from the command line output when executing unit tests. It also stops some xmls  from producing outputfiles in the project directory when unit tests are executed.

### CODE REVIEW

**Comment by MaxNoe** [comment]
Can you have a look into the first test in `src/test/java/fact/io/zfits/TestZFitsStream.java` i'm not quite sure i resolved the merge conflict correctly

**Comment by mackaiver** [comment]
The merge looks good to me. Tests run fine. Did you notice anything suspicious?

**Comment by MaxNoe** [comment]
No, just was't sure of the intended behaviour

**Comment by relleums** [comment]
I fully support the unit tests to be as silent as possible. At least with my work flow it is currently tedious to learn from the unit test stdoutput when my new tests in question failed.

**Pull request merged**
