### PR TITLE
Timelapse calibration

### PR DESCRIPTION
**Pull request by MaxNoe**
This adds Processors to be able to do DRS4 Calibration like MAGIC does it.

Code to produce the calibration fits file is here: https://github.com/fact-project/timelapse_calibration

A file calculated with the run `20160728_018.fits.fz` is attached. Note that a few fits failed in this file.
We need to take more data to get better results.

### CODE REVIEW

**Comment by MaxNoe** [comment]
Some plots to illustrate:

## General Idea

In drs4 chips, there is a clear dependency between the time since a cell was last read out and its offset value:
fit_result_p0_c0

This can be parameterized as `offset = a * delta_t ^ b + c`. In the plot you can see the fit result for Pixel 0, Cell 0.

## Results

Here are some FACT-Tools Viewer results comparing `DrsTimelapseCalibration` calibrated data to our traditional `DrsCalibration`. Note that tha calibration file is only valid for the period after the FAD Board was changed. You can see the effect in the lower left of the camera if you look into the standard test file.

calibration_result

**Comment by dneise** [comment]
I think one should somehow stress the fact, that this TimelapseCalibration in a sense indends to make the jump correction obsolete.

So it might be interesting to show an event containing a nicely visible jump with
 * std drs amplitude calib --> jump visible
 * after jump correction --> no jump
 * alternatively after Timelapse --> also no jump(?)

**Comment by MaxNoe** [comment]
Here an example:

jump

Blue TimelapseCalibration, Cyan conventional DrsCalibration, Red Conventional + JumpCorrection

**Comment by MaxNoe** [comment]
jump2

**Comment by MaxNoe** [comment]
jump3

**Comment by dneise** [comment]
Something seems wrong, can you confirm the name - color relation again?

**Comment by MaxNoe** [comment]
Yes, colors are correct. You can also see the labels (DataRemoved = After JumpRemoval)

**Comment by MaxNoe** [comment]
This is to WIP

**Pull request closed without merging**
