### PR TITLE
Update auxfileservice

### PR DESCRIPTION
**Pull request by mackaiver**
With this update you can simply specify the path to a folder containing all the auxiliary files in its subfolders. Like this basically:

```
<service id="auxService" class="fact.auxservice.AuxFileService" auxFolder="file:/fact/aux/2015" />
.
.
.
<fact.features.source.SourcePosition    outputKey="sourcePosition"    auxService="auxService" />
``` 

Also, and this might be important, currently this thing updates its file list every 12 hours. I hope this is useful for long running fact-tools processes like the RTA. In other words: This will scan the whole filesystem below the path you specified.

### CODE REVIEW

**Comment by mackaiver** [comment]
Hello. Someone willing to test and review this? Would be awesome.

**Comment by MaxNoe** [comment]
I don't really get why it is necessary to parse the whole filesystem below `auxFolder`.
We have a `YYYY/MM/DD` structure everywhere we have those files (or could simply create it for e.g. unit tests).

Then one could simply look up the file only for the requested timestamp.

**Comment by mackaiver** [comment]
Look at this now. It just checks for the file. Needs to be in the canonical file structure. Added some minor things as well.

**Comment by MaxNoe** [comment]
I fucked up with git, good version is #200

**Pull request closed without merging**
