### PR TITLE
Jpmml

### PR DESCRIPTION
**Pull request by mahnen**
Hi Guys,

I like this feature very much, please merge.

### CODE REVIEW

**Comment by jebuss** [comment]
+1

**Comment by jebuss** [comment]
@fact-project/fact-tools-core-dev to me it seems that this can be merged, agree?

**Comment by MaxNoe** [comment]
Version number in `pom.xml` and `CHANGELOG.md` please

**Comment by mackaiver** [comment]
This branch was still very much WIP. There have been no unit tests yet. I've been doing this diffrently in the RTA branch and planned to merge this back. Also I felt there were some problems with the pmml-evaluator library version I used in this branch.

**Comment by MaxNoe** [comment]
Why did you not write this, when this Pull Request was opened?

**Comment by mackaiver** [comment]
Because I'm in Paris at the moment.

**Pull request merged**
