### PR TITLE
Update authors

### PR DESCRIPTION
**Pull request by MaxNoe**
This file is horribly outdated and the same information is in the pom, the zenodo.json and the git history.

### CODE REVIEW

**Comment by jebuss** [comment]
I suggest to add Michael Bulinski to the developers in the POM.xml

**Comment by MaxNoe** [comment]
He does not appear here: https://github.com/fact-project/fact-tools/graphs/contributors

This means he has no contributions to the Master, this is why he is missing. Which is strange, because he should have contributions. Maybe a missing email in his github config, I will check.

**Comment by MaxNoe** [comment]
This is the full author list:

```
$ git shortlog --summary --numbered -e
   482  Maximilian Nöthe <maximilian.noethe@tu-dortmund.de>
   355  Kai Brügge <kai.bruegge@edu.udo>
   336  Fabian Temme <fabian.temme@tu-dortmund.de>
   151  Jens Buß <jens.buss@tu-dortmund.de>
   116  Maximilian Noethe <maximilian.noethe@tu-dortmund.de>
   103  Kai Bruegge <kai.bruegge@udo.edu>
   100  Michael Bulinski <michael.bulinski@tu-dortmund.de>
    99  Kai B <kai.bruegge@tu-dortmund.de>
    96  jebuss <jens.buss@udo.edu>
    78  jens buß <jens.buss@tu-dortmund.de>
    74  Christian Bockermann <chris@jwall.org>
    74  sebastian <sebmuell@phys.ethz.ch>
    65  Kai Brügge <kai.bruegge@udo.edu>
    65  kai <bruegge@kies.cs.uni-dortmund.de>
    61  Jan Freiwald <jan.freiwald@udo.edu>
    52  Kai <kai.bruegge@gmail.com>
    45  Maximilian Noethe <maximilian.noethe@udo.edu>
    34  Kai Bruegge <kai.bruegge@tu-dortmund.de>
    32  Jens Buss <jens.buss@tu-dortmund.de>
    32  jebuss <jens.buss@tu-dortmund.de>
    28  Dominik Neise <neised@phys.ethz.ch>
    26  Kai Brügge <kai.bruegge@tu-dortmund.de>
    24  lena <lena.linhoff@googlemail.com>
    21  Alexey Egorov <aegorov87@gmail.com>
    20  kai <bruegge@kimba.cs.uni-dortmund.de>
    19  Hendrik Hildebrandt <s58237@yahoo.com>
    19  Katie Gray <grayka@whitman.edu>
    18  MacKaiver <mackaiver@freenet.de>
    17  Dominik Baack <dominik.baack@udo.edu>
    16  Lena <lena.linhoff@googlemail.com>
    16  jens buß <jebuss@E5b-Mac-mini-020.local>
    14  Dominik Neise <dominik.neise@udo.edu>
    12  Max Ahnen <m.knoetig@gmail.com>
    11  Dominik <rangarik_91@yahoo.de>
    11  kai <bruegge@kick.cs.uni-dortmund.de>
    10  Lena Linhoff <lena.linhoff@googlemail.com>
     8  kschennetten <kschennetten@udo.edu>
     7  Jens Buss <jens.buss@udo.edu>
     7  jbuss <jens.buss@udo.edu>
     6  Lena Linhoff <lena@Lenas-Mac-mini.local>
     6  Sebastian A. Mueller <sebmuell@phys.ethz.ch>
     6  ftemme <fabian.temme@tu-dortmund.de>
     6  mackaiver <mackaiver@freenet.de>
     5  Kai MacGyver <kai@Kais-Mac-mini.local>
     5  lena-lin <lena.linhoff@googlemail.com>
     5  mahnen <m.knoetig@gmail.com>
     4  Dominik <test.test@test.test>
     3  Dominik Neise <dneise@hasseroeder.(none)>
     3  Jens Buss <jens.buss@online.de>
     2  Christian Bockermann <christian.bockermann@udo.edu>
     2  Dominik B <ardion_91@yahoo.de>
     2  Max <max@max-UX32VD.(none)>
     2  Maximilian Nöthe <maximilian.noethe@udo.edu>
     2  kai <bruegge@kieker>
     1  Alexey <alexey.egorov@tu-dortmund.de>
     1  Matyro <dominik.baack@udo.edu>
     1  Niklas Wulf <niklas@wulf-home.de>
     1  fact_opr <fact_tools@isdc-nx00.isdc.unige.ch>
     1  fact_opr <fact_tools@isdc-nx01.isdc.unige.ch>
     1  kai <bruegge@kilt.cs.uni-dortmund.de>
     1  kai <kai.bruegge@udo.edu>
     1  mackaiver <kai.bruegge@tu-dortmund.de>
     1  mknoetig <mknoetig@phys.ethz.ch>
```

It seems some emails are missing in github accounts, e.g. `Michael Bulinski <michael.bulinski@tu-dortmund.de>`

**Comment by jebuss** [comment]
> He does not appear here: https://github.com/fact-project/fact-tools/graphs/contributors

He does now. Just checked it. He is number 5. Strange!

**Comment by tarrox** [comment]
> He does now. Just checked it. He is number 5. Strange!
I added my additional emails to my profile, after max figured out that this was the error. So not that Strange^^.

**Comment by jebuss** [comment]
I see

**Comment by MaxNoe** [comment]
I updated all author metadata, please check everybody

**Comment by MaxNoe** [comment]
Thanks to the `.mailmap` file, this now looks nice:

```
$ git shortlog --no-merges --summary --numbered --email
   730  Kai Brügge <kai.bruegge@tu-dortmund.de>
   501  Maximilian Nöthe <maximilian.noethe@tu-dortmund.de>
   360  Jens Buß <jens.buss@tu-dortmund.de>
   290  Fabian Temme <fabian.temme@tu-dortmund.de>
    95  Michael Bulinski <michael.bulinski@tu-dortmund.de>
    73  Sebastian A. Mueller <sebmuell@phys.ethz.ch>
    61  Christian Bockermann <chris@jwall.org>
    51  Lena Linhoff <lena.linhoff@tu-dortmund.de>
    50  Jan Freiwald <jan.freiwald@udo.edu>
    40  Dominik Neise <neised@phys.ethz.ch>
    30  Dominik Baack <dominik.baack@tu-dortmund.de>
    21  Alexey Egorov <alexey.egorov@tu-dortmund.de>
    17  Hendrik Hildebrandt <s58237@yahoo.com>
    16  Katie Gray <grayka@whitman.edu>
    14  Max L. Ahnen <m.knoetig@gmail.com>
     8  Kai Schenetten <kai.schenetten@tu-dortmund.de>
     1  Niklas Wulf <niklas@wulf-home.de>
```

**Pull request merged**
