### PR TITLE
Reimplement conc core

### PR DESCRIPTION
**Pull request by MaxNoe**
This reimplements ConcCore without copying the MARS code verbatim and without sticking to 1 character variable names

### CODE REVIEW

**Comment by MaxNoe** [comment]
No. See issue #74 . We do not really expect to have the same results. 

I implemented these feauture how it is described in the comments.

**Comment by MaxNoe** [comment]
Comparison plots new and old on a Crab data run with ~18000 Events:

comparison1d
comparison2d
I think the results are similar enough and the Code is much easier to understand now.

**Comment by dneise** [comment]
Could you point to these conments in Mars you are refering to? Or, even better: point to the place in fact tools, where you explain what you define as ConcCore?

**Comment by MaxNoe** [comment]
> Could you point to these conments in Mars you are refering to? Or, even better: point to the place in fact tools, where you explain what you define as ConcCore?

In Fact-Tools this is now in the javadocs of the processor:
https://github.com/fact-project/fact-tools/pull/261/files#diff-d2718c8d2e104928d3e18a591f16e42aR38

In Mars it's here:

https://trac.fact-project.org/browser/trunk/Mars/mimage/MHNewImagePar.h#L31

**Comment by dneise** [comment]
Ah okay, I get it now .. I must say I mixed the word "ConcCore" up with "ConcCOG" since Core is also a word which expresses something "centered" ... reading then that you count all pixels with a Maha-dist < 1 did not help me, since I did not know what you used for the covariance matrix ... 

"inside the Hillas ellipsis" should have told me what was going on ... 

I know you are not responsible for the term "ConcCore" which was basically what puzzled me and reading the docstring did not help me, but sent me to wikipedia, to study the Maha-dist, just to learn, that I am missing the information about the cov-matrix.

**Pull request merged**
