### PR TITLE
Measure performance

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by alexeyegorov** [comment]
isn't it something that package streams-performance should handle? or should this one has some very special "fact" purpose?

**Comment by MaxNoe** [comment]
Honestly I have no idea.  The docstring says you and @mackaiver wrote this process. I just fixed it for multiple uses of the same processor

**Comment by alexeyegorov** [comment]
Then, we should consider differences to streams-performance. Possibly this was written while playing around with storm before CTA meeting in September. I think we may remove this class or import some of its' special functionality (if any exists) into streams-performance.

**Comment by alexeyegorov** [comment]
Actually, this is nice as it does something similar as streams-performance, but allows one to measure performance of all processors of a process container. Maybe we should think of integrating such functionality into streams-performance (@cbockermann), but at this point I think it can be merged to fact-tools.

**Pull request merged**
